# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/custom_download_strategy"
class Npssh < Formula
  desc ""
  homepage "https://github.com/nextpart/npssh"
  version "1.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nextpart/npssh/releases/download/v1.0.3/npssh_1.0.3_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy 
      sha256 "4035b0d68432d50d37276972a32a8f853a4e29530f55ee1d8e70907e479e23e3"

      def install
        bin.install "npssh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nextpart/npssh/releases/download/v1.0.3/npssh_1.0.3_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy 
      sha256 "9cab75c0ca153a3bcef68f95c89514810a70435b86cf91460c5b971046f53cc1"

      def install
        bin.install "npssh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nextpart/npssh/releases/download/v1.0.3/npssh_1.0.3_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy 
      sha256 "be427e2f22c8136762bc06956d65710647975db2ca5494fe2dd38d89d310d794"

      def install
        bin.install "npssh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nextpart/npssh/releases/download/v1.0.3/npssh_1.0.3_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryDownloadStrategy
      sha256 "b1e6ff252c2afca612deebac97ca771afc2b25ef08e1498d5772f2c16c5774c2"

      def install
        bin.install "npssh"
      end
    end
  end
end
