# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Npssh < Formula
  desc ""
  homepage "https://github.com/nextpart/npssh"
  version "1.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nextpart/npssh/releases/download/v1.0.2/npssh_1.0.2_Darwin_arm64.tar.gz"
      sha256 "7859be5053ebb39ea2cc82ea13d2c959e76a5e850173b8b3e442cc38af9879a4"

      def install
        bin.install "npssh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nextpart/npssh/releases/download/v1.0.2/npssh_1.0.2_Darwin_x86_64.tar.gz"
      sha256 "3e510e7671853c2bb8e496702eff46eb841735dcce66ffffb2edd46cbca07ca3"

      def install
        bin.install "npssh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nextpart/npssh/releases/download/v1.0.2/npssh_1.0.2_Linux_arm64.tar.gz"
      sha256 "8f4d1fbd9f94a76d7f4dc492c48f211dd1d5e511a8dd4c9c59c0e25cde9d6b62"

      def install
        bin.install "npssh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nextpart/npssh/releases/download/v1.0.2/npssh_1.0.2_Linux_x86_64.tar.gz"
      sha256 "531970843bab55d660020fb8fb3b6da31daa5e9626a18df7ac55b9b5578c203b"

      def install
        bin.install "npssh"
      end
    end
  end
end
